(()=>{var a={};a.id=175,a.ids=[175],a.modules={223:()=>{},846:a=>{"use strict";a.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},923:(a,b,c)=>{"use strict";c.d(b,{Y:()=>i,g:()=>h});let d=require("fs");var e=c.n(d),f=c(3873),g=c.n(f);function h(){var a,b;return(b=a=g().join(process.cwd(),"app","blog","posts"),e().readdirSync(b).filter(a=>".mdx"===g().extname(a))).map(b=>{var c,d;let f,h,i,j,k,{metadata:l,content:m}=(c=g().join(a,b),d=e().readFileSync(c,"utf-8"),h=(f=/---\s*([\s\S]*?)\s*---/).exec(d)[1],i=d.replace(f,"").trim(),j=h.trim().split("\n"),k={},j.forEach(a=>{let[b,...c]=a.split(": "),d=c.join(": ").trim();d=d.replace(/^['"](.*)['"]$/,"$1"),k[b.trim()]=d}),{metadata:k,content:i});return{metadata:l,slug:g().basename(b,g().extname(b)),content:m}})}function i(a,b=!1){let c=new Date;a.includes("T")||(a=`${a}T00:00:00`);let d=new Date(a),e=c.getFullYear()-d.getFullYear(),f=c.getMonth()-d.getMonth(),g=c.getDate()-d.getDate(),h="";h=e>0?`${e}y ago`:f>0?`${f}mo ago`:g>0?`${g}d ago`:"Today";let j=d.toLocaleString("en-us",{month:"long",day:"numeric",year:"numeric"});return b?`${j} (${h})`:j}},1577:(a,b,c)=>{"use strict";c.r(b),c.d(b,{baseUrl:()=>e,default:()=>f});var d=c(923);let e="https://portfolio-blog-starter.vercel.app";async function f(){let a=(0,d.g)().map(a=>({url:`${e}/blog/${a.slug}`,lastModified:a.metadata.publishedAt}));return[...["","/blog"].map(a=>({url:`${e}${a}`,lastModified:new Date().toISOString().split("T")[0]})),...a]}},2290:(a,b,c)=>{"use strict";c.r(b),c.d(b,{patchFetch:()=>o,routeModule:()=>k,serverHooks:()=>n,workAsyncStorage:()=>l,workUnitAsyncStorage:()=>m});var d={};c.r(d),c.d(d,{GET:()=>j});var e=c(7303),f=c(1808),g=c(3071),h=c(1577),i=c(923);async function j(){let a=(await (0,i.g)()).sort((a,b)=>new Date(a.metadata.publishedAt)>new Date(b.metadata.publishedAt)?-1:1).map(a=>`<item>
          <title>${a.metadata.title}</title>
          <link>${h.baseUrl}/blog/${a.slug}</link>
          <description>${a.metadata.summary||""}</description>
          <pubDate>${new Date(a.metadata.publishedAt).toUTCString()}</pubDate>
        </item>`).join("\n");return new Response(`<?xml version="1.0" encoding="UTF-8" ?>
  <rss version="2.0">
    <channel>
        <title>My Portfolio</title>
        <link>${h.baseUrl}</link>
        <description>This is my portfolio RSS feed</description>
        ${a}
    </channel>
  </rss>`,{headers:{"Content-Type":"text/xml"}})}let k=new e.AppRouteRouteModule({definition:{kind:f.RouteKind.APP_ROUTE,page:"/rss/route",pathname:"/rss",filename:"route",bundlePath:"app/rss/route"},distDir:".next",projectDir:"",resolvedPagePath:"/Users/austin/Documents/VSCode/portfolio-starter-kit/app/rss/route.ts",nextConfigOutput:"",userland:d}),{workAsyncStorage:l,workUnitAsyncStorage:m,serverHooks:n}=k;function o(){return(0,g.patchFetch)({workAsyncStorage:l,workUnitAsyncStorage:m})}},3033:a=>{"use strict";a.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},3431:()=>{},3873:a=>{"use strict";a.exports=require("path")},4870:a=>{"use strict";a.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},7303:(a,b,c)=>{"use strict";a.exports=c(4870)},9294:a=>{"use strict";a.exports=require("next/dist/server/app-render/work-async-storage.external.js")}};var b=require("../../webpack-runtime.js");b.C(a);var c=a=>b(b.s=a),d=b.X(0,[71],()=>c(2290));module.exports=d})();